---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.name: elasticsearch
  name: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.name: elasticsearch
  name: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: tcp-9200
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: tcp-9300
  selector:
    app.name: elasticsearch
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.name: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: elasticsearch
  template:
    metadata:
      labels:
        app.name: elasticsearch
    spec:
      serviceAccount: elasticsearch
      containers:
        - name: elasticsearch
          image: elasticsearch:7.9.2
          imagePullPolicy: Never
          resources:
            limits:
              memory: "2.5Gi"
            requests:
              memory: "2.5Gi"
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
