---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8820"
    app.quarkus.io/commit-id: 3c13b730f2c8150c92be12a2940035d61582f9b6
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:23:57 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imagethumbnail
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imagethumbnail
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8820"
    app.quarkus.io/commit-id: 3c13b730f2c8150c92be12a2940035d61582f9b6
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:23:57 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imagethumbnail
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imagethumbnail
spec:
  ports:
    - port: 8820
      targetPort: 8820
      name: tcp-8820
  selector:
    app.kubernetes.io/name: imagethumbnail
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8820"
    app.quarkus.io/commit-id: 3c13b730f2c8150c92be12a2940035d61582f9b6
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:23:57 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imagethumbnail
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imagethumbnail
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imagethumbnail
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8820"
        app.quarkus.io/commit-id: 3c13b730f2c8150c92be12a2940035d61582f9b6
        app.quarkus.io/build-timestamp: 2020-09-30 - 19:23:57 +0000
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: imagethumbnail
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      serviceAccount: imagethumbnail
      containers:
        - name: imagethumbnail
          image: malcolmpereira/imagethumbnail-quarkus-jvm
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "0.25"
              memory: "756Mi"
            requests:
              cpu: "0.25"
              memory: "756Mi"
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IMAGE_RABBITMQ_HOST
              value: rabbitmq
            - name: IMAGE_RABBITMQ_USERNAME
              value: imageapi
            - name: IMAGE_RABBITMQ_PASSWORD
              value: secret
            - name: JAEGAR_HOST
              value: http://jaeger:14268/api/traces
            - name: LOGSTASH_HOST
              value: logstash
          ports:
            - containerPort: 8820
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/live
              port: 8820
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: 8820
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
