---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8830"
    app.quarkus.io/commit-id: 7d403d920d668c9a379802cc7496e4d0229f1ce6
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:29:36 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imagestorage
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imagestorage
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8830"
    app.quarkus.io/commit-id: 7d403d920d668c9a379802cc7496e4d0229f1ce6
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:29:36 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imagestorage
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imagestorage
spec:
  ports:
    - port: 8830
      targetPort: 8830
      name: tcp-8830
  selector:
    app.kubernetes.io/name: imagestorage
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8830"
    app.quarkus.io/commit-id: 7d403d920d668c9a379802cc7496e4d0229f1ce6
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:29:36 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imagestorage
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imagestorage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imagestorage
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8830"
        app.quarkus.io/commit-id: 7d403d920d668c9a379802cc7496e4d0229f1ce6
        app.quarkus.io/build-timestamp: 2020-09-30 - 19:29:36 +0000
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: imagestorage
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      serviceAccount: imagestorage
      containers:
        - name: imagestorage
          image: malcolmpereira/imagestorage-quarkus-native
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "0.25"
              memory: "32Mi"
            requests:
              cpu: "0.25"
              memory: "32Mi"
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IMAGE_RABBITMQ_HOST
              value: rabbitmq
            - name: IMAGE_RABBITMQ_USERNAME
              value: imageapi
            - name: IMAGE_RABBITMQ_PASSWORD
              value: secret
            - name: IMAGEAPI_DB_HOST
              value: postgresql
            - name: JAEGAR_HOST
              value: http://jaeger:14268/api/traces
            - name: LOGSTASH_HOST
              value: logstash
          ports:
            - containerPort: 8830
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/live
              port: 8830
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: 8830
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
