---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    app.quarkus.io/commit-id: 137d5d55a626e768f7995d24eced5743531890e1
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:33:26 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imageapi
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imageapi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    app.quarkus.io/commit-id: 137d5d55a626e768f7995d24eced5743531890e1
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:33:26 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imageapi
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imageapi
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
      protocol: TCP
      name: tcp-31001
  selector:
    app.kubernetes.io/name: imageapi
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    app.quarkus.io/commit-id: 137d5d55a626e768f7995d24eced5743531890e1
    app.quarkus.io/build-timestamp: 2020-09-30 - 19:33:26 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: imageapi
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: imageapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imageapi
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        app.quarkus.io/commit-id: 137d5d55a626e768f7995d24eced5743531890e1
        app.quarkus.io/build-timestamp: 2020-09-30 - 19:33:26 +0000
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: imageapi
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      serviceAccount: imageapi
      containers:
        - name: imageapi
          image: malcolmpereira/imageapi-quarkus-native
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "0.25"
              memory: "15Mi"
            limits:
              cpu: "0.25"
              memory: "15Mi"
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IMAGE_API_ORIGINS
              value: http://localhost:31000
            - name: IMAGEVALIDATION_SERVICE
              value: http://imagevalidation:8810/imagevalidation
            - name: IMAGETHUMBNAIL_SERVICE
              value: http://imagethumbnail:8820/imagesampling
            - name: IMAGESTORAGE_SERVICE
              value: http://imagestorage:8830/imagestorage
            - name: JAEGAR_HOST
              value: http://jaeger:14268/api/traces
            - name: LOGSTASH_HOST
              value: logstash
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
