---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.name: imageclient
    app.version: 1.0.0-SNAPSHOT
  name: imageclient
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.name: imageclient
    app.version: 1.0.0-SNAPSHOT
  name: imageclient
spec:
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 31000
      protocol: TCP
      name: tcp-31000
  selector:
    app.name: imageclient
    app.version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.name: imageclient
    app.version: 1.0.0-SNAPSHOT
  name: imageclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: imageclient
      app.version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.name: imageclient
        app.version: 1.0.0-SNAPSHOT
    spec:
      serviceAccount: imageclient
      containers:
        - name: imageclient
          image: malcolmpereira/imageclient
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "0.25"
              memory: "8Mi"
            requests:
              cpu: "0.25"
              memory: "8Mi"
          ports:
            - containerPort: 80
              protocol: TCP
