---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.name: jaeger
  name: jaeger
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.name: jaeger
  name: jaeger
spec:
  ports:
    - port: 16686
      targetPort: 16686
      protocol: TCP
      name: tcp-16686
      nodePort: 31002
    - port: 5775
      targetPort: 5775
      protocol: UDP
      name: upd-5775
    - port: 6832
      targetPort: 6832
      protocol: UDP
      name: upd-6832
    - port: 5778
      targetPort: 5778
      protocol: TCP
      name: tcp-5778
    - port: 14268
      targetPort: 14268
      protocol: TCP
      name: tcp-14268
    - port: 14250
      targetPort: 14250
      protocol: TCP
      name: tcp-14250
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: tcp-9411
  selector:
    app.name: jaeger
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.name: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: jaeger
  template:
    metadata:
      labels:
        app.name: jaeger
    spec:
      serviceAccount: jaeger
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.18
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "0.15"
              memory: "64Mi"
            requests:
              cpu: "0.15"
              memory: "64Mi"
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
