---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.name: logstash
  name: logstash
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.name: logstash
  name: logstash
spec:
  ports:
    - port: 12201
      targetPort: 12201
      protocol: UDP
      name: udp-12201
    - port: 5000
      targetPort: 5000  
      protocol: TCP
      name: tcp-5000
    - port: 9600
      targetPort: 9600
      protocol: TCP  
      name: tcp-9600
  selector:
    app.name: logstash
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.name: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: logstash
  template:
    metadata:
      labels:
        app.name: logstash
    spec:
      serviceAccount: logstash
      containers:
        - name: logstash
          image: logstash:7.9.2
          imagePullPolicy: Never
          # resources:
          #   limits:
          #     cpu: "1.0"
          #     memory: "512Mi"
          #   requests:
          #     cpu: "1.0"
          #     memory: "512Mi"
          env:
            - name: config.string
              value: '
                input {
                  gelf {
                    port => 12201
                  }
                }
                output {
                  stdout {}
                  elasticsearch {
                    hosts => ["http://elasticsearch:9200"]
                  }
                }
              '
          ports:
            - containerPort: 12201
              protocol: UDP
            - containerPort: 5000
              protocol: TCP
            - containerPort: 9600
              protocol: TCP  
      
